# Generated by Django 5.1.3 on 2024-11-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_app', '0004_carts_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
